# tragen_dict.py
# This module is actually just a dictionary with some
# namedtuples. It is not meant to be script or library
# rather, it is merely for storage of the data.

from collections import namedtuple, OrderedDict
from functools import singledispatch
import json


from cytoolz import valmap


word = namedtuple('word', 'id text type_gender definition etymology')
etymology = namedtuple('etymology', 'type ref text')

words = OrderedDict([
    ("A", [
word("adi", "adi", "SUF", "mediopassive suffix", None),
word("agai", "agaî", "m", "feast, holiday", None),
word("agaisu", "agaî", "sú", "to hold a feast, celebrate a holiday", None),
word("agaidi", "ägaîdi", "g", "festive song, carol",
     [etymology("word", "#agai", "agaî"),
      etymology("word", "#dizhe", "di(ʒe)")]),
word("agaiora", "ägaî'ôra", "m", "feast day",
     [etymology("word", "#agai", "agaî"),
      etymology("word", "#ora", "ôra")]),
word("aimu", "aîmu", "hy", 'same, equal', None),
word("aimusu", "aîmu", "sú", "to the same/equal", None),
word("aimupash", "aîmupaš", "ADV",  "similarly",
     [etymology("word", "#aimu", "aîmu"),
      etymology("affix", "#pash", "paš")]),
word("aimuzadisu", "aîmuzadi", "sú", "to become the same thing/one",
     [etymology("word", "#aimu", "aîmu"),
      etymology("affix", "#izadisu", "izadi")]),
word("aimuzosu", "aîmuzo", "sú", "to make the same thing",
     [etymology("word", "#aimu", "aîmu"),
      etymology("affix", "#izosu", "izo")]),
word("ainagai", "aînagaî", "m", "feast in honor of a hero",
     [etymology("word", "#aine", "aîne"),
      etymology("word", "#agai", "agaî")]),
word("aine", "aîne", "k", "hero", None),
word("ainedi", "aînedi", "m", "'Song of the Hero', epic",
     [etymology("word", "#aine", "aîne"),
      etymology("word", "#dizhe", "di(ʒe)")]),
word("ainezadisu", "aînezadi", "sú", "to become a hero",
     [etymology("word", "#aine","aîne"),
      etymology("affix", "#izadisu", "izadi")]),
word("hy-aku", "âku", "hy", "strong", None),
word("aku", "âku", "g", "tree", None),
word("akukorne", "âkukôrne", "d", "tree seed",
     [etymology("word", "#aku", "âku"),
      etymology("word", "#korne", "kôrne")]),
word("akugeshi", "âkugeši", "g", "termite, wood-eater",
     [etymology("word", "#aku", "âku"),
      etymology("word", "#geshi", "geši")]),
word("akuzi", "âkuzi", "d", "wood",
     [etymology("word", "#aku", "âku"),
      etymology("word", "#zilo", "zi(lo)")]),
word("alka", "âlka", "d", "foot", None),
word("anglas", "änglas", "ADV", "in English",
     [etymology("word", "#angla", "Ângla"),
      etymology("postposition", "#es", "-es")]),
word("anglazosu", "änglazo", "sú", "anglicize",
     [etymology("word", "#angla", "Ângla"),
      etymology("affix", "#izosu", "izo")]),
word("ar", "âr", "CONJ", "that (e.g., 'I said that he was ...')", None),
word("hy-arpo", "ârpo", "hy", "old", None),
word("arpo", "ârpo", "k/l", "elder, old man/woman", None),
word("arpozadisu", "arpozadi", "sú", "to age",
     [etymology("word", "#arpo", "arpo"),
      etymology("affix", "#izadi", "izadisu")]),
word("arhga", "âŗga", "hy, j", "northwest", None),
word("arhgaka", "äŗgaka", "k", "northwesterner",
     [etymology("word", "#arhga", "âŗga"),
      etymology("postposition", "#ka", "ka")]),
word("atu", "átu", "m", "time", None),
word("avi", "âvi", "k", "father", None),
word("avina", "âvina", "k", "passed father",
     [etymology("word", "#avi", "âvi"),
      etymology("postposition", "#na", "-na")]),
word("avuli", "âvuli", "k", "grandfather",
     [etymology("word", "#avi", "âvi"),
      etymology("postposition", "#uli", "uli")]),
word("avulida", "âvulida", "k", "family member (lit. ancestor's child)",
     [etymology("word", "#avuli", "âvuli"),
      etymology("word", "#ida", "ida")]),
word("avulidad", "âvulidad", "*d", "family (lit. ancestor's descendants)",
     [etymology("word", "#avuli", "âvuli"),
      etymology("word", "#ida", "idad")]),
 ]),
    ("B", [
word("baba", "bâba", "d", "grain", None),
word("baborna", "bäbôrna", "k", "hungry",
     [etymology("word", "#baba", "bâba"),
      etymology("affix", "#orna", "ôrna")]),
word("bakosu", "báko", "sú", "drink", None),
word("bakosuga", "báko—gá", "sú", "get drunk",
     [etymology("word", "#bako", "bákosú"),
      etymology("affix", "#ga", "-gá")]),
word("bakolu", "bákolu", "m", "drink, beverage",
     [etymology("word", "#bako", "bákosú"),
      etymology("affix", "#lu", "lu")]),
word("bakowavi", "bákowávi", "m", "drinking song",
     [etymology("word", "#bako", "bákosú"),
      etymology("word", "#wavi", "wávi")]),
word("bami", "bámi", "k", "man, person", None),
word("bamina", "bámina", "k", "passed person",
     [etymology("word", "#bami", "bámi"),
      etymology("postposition", "#na", "-na")]),
word("bampovi", "bámpöví", "k, s", "my good man [often used as a polite marker for you]",
     [etymology("word", "#bami", "bámi"),
      etymology("affix", "#po", "-pö-"),
      etymology("affix", "#vihi", "ví(hi)")]),
word("bamomu", "bámômu", "d", "group of people, crowd",
     [etymology("word", "#bami", "bámi"),
      etymology("affix", "#omu", "ômu")]),
word("bamuli", "bámuli", "k", "great person",
     [etymology("word", "#bami", "bámi"),
      etymology("affix", "#uli", "uli")]),
word("basi", "bási", "j", "lake", None),
word("hy-basi", "bäsi", "hy", "of/from/relating to a/the lake",
     [etymology("word", "#basi", "bási")]),
word("basira", "bäsira", "k", "person from/living near",
     [etymology("word", "#basi", "bási"),
      etymology("word", "#ra", "ra")]),
word("basizyv", "bäsizyv", "m", "lake flower",
     [etymology("word", "#basi", "bási"),
      etymology("word", "#zyv", "zyv")]),
word("besu", "bê-", "sú", "to remove", None),
word("bebyladisu", "bêbyladi", "sú", "to be evicted, lose one's house",
     [etymology("affix", "#besu", "bê-"),
      etymology("word", "#byli", "byli"),
      etymology("affix", "#adi", "adi")]),
word("beka", "beka", "g", "horse", None),
word("bekashedisu", "bêkašedi", "sú", "to downsize",
     [etymology("affix", "#besu", "bê-"),
      etymology("word", "#kashe", "kaše"),
      etymology("affix", "#adi", "adi")]),
word("bekra", "bëkra", "k", "horseman, equestrian",
     [etymology("word", "#beka", "beka"),
      etymology("word", "#ra", "ra")]),
word("benu", "benu", "hy", "dead, killed", None),
word("benuzadisu", "benuzadi", "sú", "to commit suicide",
     [etymology("word", "#benu", "benu"),
      etymology("affix", "#izadisu", "izadi")]),
word("benuzosu", "benuzo", "sú", "to kill, murder",
     [etymology("word", "#benu", "benu"),
      etymology("affix", "#izosu", "izo")]),
word("berelivasu", "bêréliva", "sú", "to demilitarize",
     [etymology("affix", "#besu", "bê-"),
      etymology("word", "#reliva", "réliva")]),
word("bi", "bí", "CONJ", "so that", None),
word("bizosu", "bízo", "sú", "let (allow)",
     [etymology("postposition", "#bi", "bí"),
      etymology("affix", "#izosu", "izo")]),
word("bizolbu", "bízolbu", "hy", "permissible",
     [etymology("word", "#bizosu", "bízo"),
      etymology("affix", "#elbu", "elbu")]),
word("bizolu", "bízolu", "hy", "permitted",
     [etymology("word", "#bizosu", "bízo"),
      etymology("affix", "#lu", "lu")]),
word("bobe", "bôbe", "d", "coin, money", None),
word("bobumo", "bôbumo", "k", "rich (person), 'money holder'",
     [etymology("word", "#bobe", "bôbe"),
      etymology("word", "#umo", "umo")]),
word("boladigo", "boladîgo", "m", "adventure, journey, odyssey", None),
word("bolchakso", "Bölča-kso", "k", "a name of God, in the sense of comforter or protector",
     [etymology("word", "#bó", "bó"),
      etymology("postposition", "#il", "il"),
      etymology("affix", "#cha", "ča")]),
word("bosto", "bosto", "hy, j", "northeast", None),
word("bostoka", "böstoka", "hy, k*", "north-easterner",
     [etymology("word", "#bosto", "bosto"),
      etymology("postposition", "#ka", "ka")]),
word("braila", "braîla", "j", "hill, large bump", None),
word("braileto", "braîleto", "j", "bump, small hill",
     [etymology("word", "#braila", "braîla"),
      etymology("affix", "#eto", "eto")]),
word("bula", "búla", "g", "cow, cattle", None),
word("bulazi", "búlazi", "d", "beef",
     [etymology("word", "#bula", "búla"),
      etymology("affix", "#zilo", "zi(lo)")]),
word("buz", "buz", "POST", "close, near, around", None),
word("buze", "buze", "j", "surrounding area", None),
word("bylem", "bylem", "hy", "homeless",
     [etymology("word", "#byli", "byli"),
      etymology("postposition", "#em", "-em")]),
word("byli", "byli", "j", "house", None),
word("bylomu", "bylomu", "j", "town, village",
     [etymology("word", "#byli", "byli"),
      etymology("affix", "#omu", "ômu")]),
word("bylomuli", "bylômuli", "j", "city, large town",
     [etymology("word", "#byli", "byli"),
      etymology("affix", "#omu", "ômu"),
      etymology("affix", "#uli", "uli")]),
word("bylomyto", "bylômyto", "j", "small town, village",
     [etymology("word", "#byli", "byli"),
      etymology("affix", "#omu", "ômu"),
      etymology("affix", "#eto", "eto")])]),
    ("C", [
word("cadesha", "cadeša", "hy", "prone to drinking/getting drunk (drunkard)",
     [etymology("affix", "#ca", "ca"),
      etymology("word",  "#desha", "deša")]),
word("cakashe", "cakaše", "hy", "ambitious, prone to attempting many things",
     [etymology("affix", "#ca", "ca"),
      etymology("word",  "#kashe", "kaše")]),
word("caku", "cakû", "hy", "overly prone to, busy, addict(ive)",
     [etymology("affix", "#ca", "ca"),
      etymology("affix", "#ku", "kû")]),
word("cakuge", "cakuge", "hy", "prone to using a weapon/fighting",
     [etymology("affix", "#ca", "ca"),
      etymology("word",  "#kuge", "kuge")]),
word("caneki", "canéki", "hy", "prone to winning",
     [etymology("affix", "#ca", "ca"),
      etymology("word",  "#neki", "néki")]),
word("canekiha", "canékihá", "hy", "prone to conquering",
     [etymology("affix", "#ca", "ca"),
      etymology("word",  "#nekiha", "néki-há")]),
word("caple", "caple", "hy", "prone to liking",
     [etymology("affix", "#ca", "ca"),
      etymology("affix", "#ple", "ple")]),
word("careli", "caréli", "hy", "prone to war, ~belligerent, ~pugnacious",
     [etymology("affix", "#ca", "ca"),
      etymology("word",  "#reli", "réli")]),
word("caroma", "carôma", "hy", "prone to working/laboring",
     [etymology("affix", "#ca", "ca"),
      etymology("word",  "#roma", "rôma")]),
word("caromaku", "carômakû", "k, hy", "workaholic",
     [etymology("word", "#caroma", "carôma"),
      etymology("affix", "#ku", "kû")]),
word("carunotesa", "carunotêsa", "hy", "prone to speaking in/using jargon/slang",
     [etymology("affix", "#ca", "ca"),
      etymology("word",  "#runotesa", "runotêsa")]),
word("carhdosha", "caŗdoša", "hy", "productive",
     [etymology("affix", "#ca", "ca"),
      etymology("word",  "#erhdosha", "eŗdoša")]),
word("catesa", "catêsa", "hy", "loquacious",
     [etymology("affix", "#ca", "ca"),
      etymology("word",  "#tesa", "tesa")]),
word("cavolpykuzo", "cavolpykûzo", "hy", "prone to overcomplicating",
     [etymology("affix", "#ca", "ca"),
      etymology("word",  "#hyvolpyku", "volpykû"),
      etymology("affix", "#izosu", "izo")]),
word("cavolpyzo", "cavolpyzo", "hy", "prone to complicating",
     [etymology("affix", "#ca", "ca"),
      etymology("word",  "#volpyzosu", "volpyzo")]),
word("cu", "cu", "CONJ", "because", None),
word("cu-post", "cu", "POST", "because of", None),
word("Cude", "Cúde", "kso", "abbreviation of Þásúdemuhá",
     [etymology("word", "#Thasudemuha", "Þásúdemuhá")]),
]),
    ("Č", [
word("chy", "čó, čy", "DEM", "all", None)
]),
    ("D", [
word("da-part", "da", "PART", "question marker", None),
word("da-post", "da", "POST", "about", None),
word("daki", "dáki", "j", "barn, warehouse", None),
word("daksavosu", "daksâvo", "sú", "foresee",
     [etymology("postposition",  "#undak", "dak"),
      etymology("word",  "#savosu", "sâvo")]),
word("demusu", "dêmu", "sú", "chase", None),
word("demusuha", "dêmu--há", "sú", "chase after",
     [etymology("word", "#demusu", "dêmu"),
      etymology("affix", "#ha", "-há")]),
word("Derdhuli", "Derð(ul)i", "k", "Edward",
     [etymology("word", "", "from Kébh: Ëjdóh-äwréd (wealth holder)")]),
word("desha", "deša", "sú", "without an enemy, unopposed", None),
word("deshalu", "dešalu", "m", "drink, beverage",
     [etymology("word", "#desha", "deša"),
      etymology("affix", "#lu", "lu")]),
word("dewa", "dewa", "hy, j", "east", None),
word("dewaka", "dëwaka", "hy, k", "eastern(er)",
     [etymology("word", "#dewa", "dewa"),
      etymology("postposition", "#ka", "ka")]),
word("dezo", "dézo", "hy", "great", None),
word("dizhesu", "diʒe", "sú", "to sing", None),
word("dizhesuga", "diʒe-gá", "sú", "perform (musical)",
     [etymology("word", "#dizhesu", "diʒe"),
      etymology("affix", "#ga", "gá")]),
word("dizhelu", "diʒelu", "g", "song",
     [etymology("word", "#dizhesu", "diʒe"),
      etymology("affix", "#lu", "lu")]),
word("drhodzhe", "dŗôdʒe", "d", "mud", None),
word("drhozi", "dŗózi", "hy, d*", "(made of) mud",
     [etymology("word", "#drhodzhe", "dŗôdʒe"),
      etymology("affix", "#zilo", "zi(lo)")]),
word("dy", "dy-", "DEM", "no, none", None),
word("dyme", "dyme", "l", "childless woman",
     [etymology("affix", "#dy", "dy"),
      etymology("word", "#mebu", "mébu")]),
word("dypsi", "dypsi", "hy", "incompetent",
     [etymology("affix", "#dy", "dy"),
      etymology("affix", "#epsi", "epsi")]),
word("dzharhsedhro", "dʒáŗsêðro", "m", "'sweet ethos', positive atmosphere, ~ eo 'bela etoso'",
     [etymology("word", "#dzharhsi", "dʒáŗsi"),
      etymology("word", "#edhro", "êðro")]),
word("dzharhsi", "dʒáŗsi", "hy", "sweet", None),
word("Dzherhzuli", "Dʒêŗzûli", "j", "New Jersey", None)]),
    ("Ð", [
word("dhara", "ðára", "j", "path", None),
word("dheba", "ðeba", "m", "plague, tragedy", None),
word("dhir", "ðír", "PART", "Used to mark that the preceding phrase is a thought or opinion.", None),
word("dhu", "ðu", "POST", "to (dat.)", None)]),
    ("E", [
word("edhro", "êðro", "m", "air", None),
word("egi", "(h)égi", "g", "ice", None),
word("egbami", "ëgbámi", "g", "snowman",
     [etymology("word", "#egi", "égi"),
      etymology("word", "#bami", "bámi")]),
word("egira", "egira", "k", "ice-man, man who delivers ice",
     [etymology("word", "#egi", "égi"),
      etymology("word", "#ra", "ra")]),
word("egizadisu", "egizadi", "sú", "freeze (intrans.)",
     [etymology("word", "#egi", "égi"),
      etymology("affix", "#izadi", "izadi")]),
word("egizosu", "egizo", "sú", "freeze (trans.)",
     [etymology("word", "#egi", "égi"),
      etymology("affix", "#izo", "izo")]),
word("epsisu", "epsi", "sú", "to be able", None),
word("epsi", "epsi", "hy, SUF", "able", None),
word("epsu", "epsú", "q", "ability",
     [etymology("affix", "#epsi", "epsi"),
      etymology("affix", "#su", "sú")]),
word("erhdosha", "eŗdóša", "k", "producer", None),
word("erhdoshasu", "eŗdóša", "sú", "to produce", None),
word("evi", "(h)évi", "g", "fire", None),
word("evizoto", "evizoto", "g", "match",
     [etymology("word", "#evi", "évi"),
      etymology("affix", "#izo", "izo"),
      etymology("affix", "#eto", "eto")]),
word("evizosu", "evizo", "sú", "ignite (trans)",
     [etymology("word", "#evi", "évi"),
      etymology("affix", "#izo", "izo")]),
word("evu", "(e)vu", "POST", "like, (adv. marker)", None)
]),
    ("F", [
word("Fildelfi", "Fildélfi", "j", "Philadelphia", None),
word("Fildelfibuze", "Fildëlfibuze", "j", "the Delaware Valley",
     [etymology("word",  "#Fildelfi", "Fildélfi"),
      etymology("affix", "#buze", "buze")]),
word("fokla", "fokla", "m", "play, performance", None),
word("foklasu", "fokla", "sú", "to perform",
     [etymology("word", "#fokla", "fokla")]),
word("foklavegi", "foklavégi", "k", "playwright",
     [etymology("word", "#fokla", "fokla"),
      etymology("word", "#vegi", "végi")]),
word("frolkat", "frôlka(t)", "t", "hands and feet",
     [etymology("word", "#ofra", "ôfra"),
      etymology("word", "#alka", "âlka")]),
word("funau", "funaû", "k", "fisherman",
     [etymology("word", "#ufe", "ufe"),
      etymology("word", "#nauma", "naû(ma)")]),
word("funausu", "funaû", "sú", "to fish",
     [etymology("word", "#ufe", "ufe"),
      etymology("word", "#nauma", "naû(ma)")]),
word("fuzi", "fúzi", "d", "fish (meat)",
     [etymology("word",  "#ufe", "ufe"),
      etymology("affix", "#zilo", "zi(lo)")])
]),
    ("G", [
word("gaudha", "gaûða", 'k', "chief(tain), general", None),
word("gaudhasli", "gaûðasli", "hy, k*", "bossy",
     [etymology("word", "#gaudha", "gaûða"),
      etymology("affix", "#sli", "sli")]),
word("gaudhavashe", "gaûðavaše", "k", "general-king/leader",
     [etymology("word", "#gaudha", "gaûða"),
      etymology("word", "#vashe", "vaše")]),
word("ge", "gé", "POST", 'for', None),
word("genosu", "géno", "sú", "to speak", None),
word("geno", "géno", "g", "language", None),
word("genocra", "gënocra", "k", "linguist [man of language]",
     [etymology("word",  "#geno", "geno[c]"),
      etymology("word", "#ra", "ra")]),
word("gore", "gore", "k", "runner", None),
word("goresu", "gore", "sú", "to run", None),
word("geshi", "geši", "sú", "to eat", None),
word("geshizo", "gešizo", "sú", "to feed",
     [etymology("word", "#geshi", "géši"),
      etymology("affix", "#izo", "izo")]),
word("guzdhara", "guzðára", "j", "door",
     [etymology("postposition",  "#guz", "guz"),
      etymology("word", "#dhara", "ðára")]),
word("gunla", "gunla", "g", "breath", None),
word("gunla", "gunla", "sú", "to breathe", None),
word("guz", "guz", "POST", "across, through", None),
word("gy", "gy-", "DEM", "that", None)
]),
    ("H", [
word("hy", "hy", "DEM", "that, the, {adjective marker)", None)]),
    ("I", [
word("iba", "îba", "g", "light", None),
word("ibazo", "îbazo", "g", "light switch",
     [etymology("word", "#iba", "iba"),
      etymology("affix", "#izo", "izo")]),
word("ibazosu", "îbazo", "sú", "light up, brighten",
     [etymology("word", "#iba", "iba"),
      etymology("affix", "#izo", "izo")]),
word("izadisu", "izadi", "sú", "to become",
     [etymology("affix", "#izo", "izo"),
      etymology("affix", "#adi", "adi")]),
word("izosu", "izo", "sú", "to cause, make", None),]),
    ("J", [
word("javu", "javu", "k", "enemy, opposition", None),
word("javum", "jävum", "hy", "without an enemy, unopposed",
     [etymology("word", "#javu", "javu"),
      etymology("postposition",  "#em", "-[e]m")]),
word("javusebi", "javusébi", "m", "battle, meeting of enemies",
     [etymology("word", "#javu", "javu"),
      etymology("word", "#sebi", "sébi")]),
word("javusu", "javu", "sú", "oppose", None),
word("jedo", "jédo", "d", "wealth", None),
word("jedorna", "jëdôrna", "hy", "desiring wealth, greedy",
     [etymology("word", "#jedo", "jédo"),
      etymology("affix", "#orna", "ôrna")]),
word("jele", "jéle", 'hy', "slow, tired", None),
word("jeltenga", "jéltenga", "g", "slow business",
     [etymology("word", "#jele", "jéle"),
      etymology("word", "#tenga", "tenga")]),
word("jonapo", "jonapo", "k", "neighbor", None),
word("Jonapod", "Jônapod", "d", "the Neighbors (neighboring nations)", None),
word("jonapodgenoc", "jönapodgéno", "g", "the language of a neighboring nation",
     [etymology("word", "#jonapo", "jonapo"),
      etymology("word", "#geno", "géno")])
]),
    ("K", [
word("ka", "ka", "POST", "from", None),
word("kafo", "káfo", "hy", "west", None),
word("kafoka", "käfoka", "k", "westerner",
     [etymology("word",  "#kafo", "káfo"),
      etymology("postposition", "#ka", "ka")]),
word("kafonu", "káfonu", "ADV", "westward",
     [etymology("word", "#kafo", "káfo"),
      etymology("postposition",  "#nu", "nu")]),
word("kago", "kâgo", "m", "stench, odor", None),
word("kaiva", "kaîva", "g", "word", None),
word("karisu", "kári", "sú", "be situated, sit", None),
word("kari", "kári", "d", "seat", None),
word("kashe", "káše", "hy", "much, many", None),
word("kashepsi", "kašepsi", "hy, k*", "able to do many things",
     [etymology("word", "#kashe", "kaše"),
      etymology("word", "#epsi", "epsi")]),
word("kashorna", "käšôrna", "hy", "greedy, desiring much",
     [etymology("word", "#kashe", "kaše"),
      etymology("affix", "#orna", "ôrna")]),
word("keli", "keli", "j", "valley, field", None),
word("kelkema", "këlkêma", "k", "valley-dweller",
     [etymology("word", "#keli", "kéli"),
      etymology("word", "#kema", "kêma")]),
word("kelreli", "këlréli", "m", "battle/war fought in a field/valley",
     [etymology("word", "#keli", "kéli"),
      etymology("word", "#reli", "réli")]),
word("keluli", "keluli", "j", "large valley",
     [etymology("word",  "#keli", "kéli"),
      etymology("affix", "#uli", "uli")]),
word("kemasu", "kêma", "sú", "to inhabit", None),
word("kema", "kêma", "k", "inhabitant", None),
word("kemelbu", "kêmelbu", "hy", "inhabitable",
     [etymology("word",  "#kema", "kêma"),
      etymology("affix", "#elbu", "elbu")]),
word("kesi", "kési", "m", "wind", None),
word("kezhavi", "kéʒavi", "k", "ancestor",
     [etymology("word", "#kezho", "kêʒo"),
      etymology("word", "#avi", "ávi")]),
word("kezho", "kéʒo", "d", "root", None),
word("kezhokaiva", "kéʒokaîva", "g", "root word",
     [etymology("word", "#kezho", "kêʒo"),
      etymology("word", "#kaiva", "kaîva")]),
word("ki", "kí", "SUF, CONJ", "and", None),
word("kil", "kil", "PREP, PREF", "with", None),
word("kilrenzi", "kilrénzi", "g", "corporation",
     [etymology("postposition", "#kil", "kil"),
      etymology("word", "#renzi", "rénzi")]),
word("korne", "kôrne", "d", "seed", None),
word("kremo", "krémo", "g, m", "thought", None),
word("kremovil", "krémovil", "hy", "pensive, thoughtful",
     [etymology("word", "#kremo", "krémo(v)"),
      etymology("postposition", "#il", "il")]),
word("krhemo", "kŗémo", "j", "stable, garage", None),
word("ku", "kû", "SUF", "overly", None),
word("kuge", "kuge", "d", "blade, knife", None),
word("kugeklosa", "kügeklôsa", "m", "sword-glory, renown won for expert fighting performance/skill",
     [etymology("word", "#kuge", "kuge"),
      etymology("word", "#klosa", "klôsa")]),
word("kuguli", "kuguli", "d", "sword",
     [etymology("word",  "#kuge", "kuge"),
      etymology("affix", "#uli", "uli")]),
word("kuku", "kûkû", "SUF, hy", "excessive",
     [etymology("word", "#ku", "kû")]),
word("kule", "kule", "m", "string", None),
word("kuzo", "kûzo", "hy", "overwhelming",
     [etymology("word", "#ku", "kû"),
      etymology("affix", "#izosu", "izo")]),
word("kuzosu", "kûzo", "sú", "overwhelm",
     [etymology("word", "#ku", "kû"),
      etymology("affix", "#izosu", "izo")]),
word("kyga", "kyga", "g", "dog", None),
word("kygeto", "kygeto", "g", "puppy",
     [etymology("word", "#kyga", "kyga"),
      etymology("affix", "#eto", "eto")]),
word("kygomu", "kygômu", "-c", "pack of dogs",
     [etymology("word", "#kyga", "kyga"),
      etymology("affix", "#omu", "ômu")]),
word("kyni", "kyni", "k", "family", None),
]),
    ('L', [
word('laneto', 'láneto', 'j', 'region',
     [etymology('word', '#lani', 'láni'),
      etymology('affix', '#eto', 'eto')]),
word('lani', 'láni', 'j', 'land, national territory', None),
word('lan-eri', 'Lán Êri', 'j', 'Ireland', None),
word('lan-skota', "Lán-Skôta", "j", "Scotland", None),
word("laresu", "lâre", "sú", 'to teach', None),
word("larelu", 'lârelu', 'd', 'teaching',
     [etymology("word", "#laresu", "lâre"),
      etymology("affix", "#lu", "lu")]),
word("larera", 'lârera', "k", 'teacher',
     [etymology("word", "#lare", 'lâre'),
      etymology("word", "#ra", "ra")]),
word("las", 'läs', 'ADV', 'no, not', None),
word("lasavolbu", "läsâvolbu", "hy", "invisible",
     [etymology("affix", "#las", "läs"),
      etymology("word", "#savosu", "sâvo"),
      etymology("affix", "#elbu", "elbu")]),
word("lasavopsi", "läsâvopsi", "hy", "blind",
     [etymology("affix", "#las", "läs"),
      etymology("word",  "#savosu", "sâvo"),
      etymology("affix", "#epsi", "epsi")]),
word("lasmebuzadilu", "läsmébuzadilu", "l", "woman that has not given birth",
     [etymology("affix", "#las", "läs"),
      etymology("word",  "#mebuzadisu", "mébuzadi"),
      etymology("affix", "#lu", "lu")]),
word("lemi", "lêmi", "m", "dream, rest, sleep", None),
word("lemisu", "lêmi", "sú", "to sleep, lie, dream", None),
word("lepa", "lêpa", "d", "box", None),
word("leva", "lêva", "g", "beast of burden", None),
word("levuli", "lêvuli", "g", "large beast of burden",
     [etymology("word", "#leva", "lêva"),
      etymology("affix", "#uli", "uli")]),
word("litratu", "litrátu", "m", "time of torture/hardship",
     [etymology("word",  "#litre", "litre"),
      etymology("word",  "#atu", "átu")]),
word("hy-litre", "litre", "hy", "difficult", None),
word("litre", "litre", "m", "torture", None),
word("loge", "lôge", "k", "boy", None),
word("logomu", "lôgomu", "d", "group of boys/children",
     [etymology("word",  "#loge", "lôge"),
      etymology("affix", "#omu", "ômu")]),
word("lorki", "lôrki", "j, hy", "southeast", None),
word("lorkika", "lörkika", "hy, k*", "south-easterner",
     [etymology("word",  "#lorki", "lôrki"),
      etymology("postposition", "#ka", "ka")]),
word("lu-but", "lû", "CONJ", "but", None),
word("luga", "lûga", "hy", "well", None),
word("lugazadisu", "lûgazadi", "sú", "to recuperate",
     [etymology("word",  "#luga", "lûga"),
      etymology("affix", "#izadisu", "#izadi")]),
word("lugazo", "lûgazo", "k", "doctor",
     [etymology("word",  "#luga", "lûga"),
      etymology("affix", "#izosu", "izo")]),
word("lugazosu", "lûgazo", "sú", "to cause to be well, heal",
     [etymology("word",  "#luga", "lûga"),
      etymology("affix", "#izosu", "izo")]),
word("lugazolu", "lûgazolu", "k", "cured person, patient",
     [etymology("word",  "#luga", "lûga"),
      etymology("affix", "#izosu", "izo"),
      etymology("affix", "#lu", "lu")]),
word("lushi", "luši", "m", "water", None),
word("lyga", "lyga", "ADV", "more, again", None),
word("lygalbu", "lygablu", "hy", "repeatable",
     [etymology("word", "#lyga", "lyga"),
      etymology("affix", "#elbu", "elbu")]),
word("lygorna", "lygôrna", "hy", "wanting more, greedy",
     [etymology("word",  "#lyga", "lyga"),
      etymology("affix", "#orna", "ôrna")]),
word("lymu", "lymu", "g", "animal", None),
word("lytesasu", "lytêsa", "sú", "reply",
     [etymology("affix", "#ly", "ly"),
      etymology("affix", "#tesasu", "têsa")]),
word("lyteslepa", "lytêslêpa", "d", "checkbox",
     [etymology("word", "#lytesa", "lytêslêpa"),
      etymology("word", "#lepa", "lêpa")])
    ]),
    ('M', [
word("manisu", "mâni", "sú", "to take apart", None),
word("manisusli", "mani-sli", "sú", "destroy, tear apart",
     [etymology("word", "#manisu", "máni"),
      etymology("affix", "#sli", "sli")]),
word("matesu", "mâte", "sú", "know", None),
word("matesuha", "máte–há", "sú", "know for sure",
     [etymology("word",  "#matesu", "máte"),
      etymology("affix", "#ha", "-há")]),
word("hymatelu", "mátelu", "hy", "known",
     [etymology("word", "#matesu", "máte"),
      etymology("affix", "#lu", "-lu")]),
word("matelu", "mátelu", "g", "knowledge",
     [etymology("word",  "#matesu", "máte"),
      etymology("affix", "#lu", "-lu")]),
word("mateluha", "máteluhá", "g", "certain knowledge, fact",
     [etymology("word", "#matesu", "máte"),
      etymology("affix", "#lu", "lu"),
      etymology("affix", "#ha", "-há")]),
word("mebu", "mêbu", "l", "mother", None),
word("mebuzadisu", "mêbuzadi", "sú", "to give birth, become a mother",
     [etymology("word", "#mebu", "mébu"),
      etymology("affix", "#izadisu", "izadi")]),
word("meksa", "méksa", "j, hy", "south", None),
word("meksaka", "mëksaka", "hy, k", "southerner",
     [etymology("word", "#meksa", "méksa"),
      etymology("postposition", "#ka", "ka")]),
word("Merga", "Mêrga", "j", "America", None),
word("Mergaka", "Mërgaka", "hy, k*", "American",
     [etymology("word", "#Merga", "Mêrga"),
      etymology("postposition", "#ka", "ka")]),
word("misha", "miša", "hy", "pious, ~ la. pius", None),
word("moksa", "moksa", "hy", "happy", None),
word("moksu", "moksú", "q", "happiness, to be happy",
     [etymology("word",  "#moksa", "môksa"),
      etymology("affix", "#su", "sú")]),
word("moqa", "môqa", "g", "cat", None),
word("mupege", "mupége", "m", "sadness", None),
word("mupeguli", "mupéguli", "m", "sorrow",
     [etymology("word", "#mupege", "mupége"),
      etymology("affix", "#uli", "uli")]),
word("my", "my-", "DEM", "any", None),
]),
    ('N', [
word('nada', 'náda', 'hy', 'north', None),
word("nadaka", "nädaka", "hy, k*", "northerner",
     [etymology("word", "#nada", "náda"),
      etymology("affix", "#ka", "ka")]),
word("naknosu", "nákno", "sú", "to crawl", None),
word("nasha", "náša", "d", "peace", None),
word("nashorna", "näšôrna", "hy", "desiring peace",
     [etymology("word",  "#nasha", "naša"),
      etymology("affix", "#orna", "ôrna")]),
word("nauma", "naûma", "k", "thief", None),
word("naumasu", "naûma", "sú", "take, steal", None),
word("neki", "néki", "m", "victory", None),
word("nekisu", 'néki', "sú", 'to win', None),
word("nekiha", "nékihá", "k", "conquerer",
     [etymology("word", "#nekisu", "néki"),
      etymology("affix", "#ha", "há")]),
word("nekisuha", "nékihá", "sú", "to conquer",
     [etymology("word", "#nekisu", "néki"),
      etymology("affix", "#ha", "há")]),
word("nekisli", "nékisli", "m", "bittersweet victory",
     [etymology("word", "#neki", "néki"),
      etymology("affix", "#sli", "sli")]),
word("nodhe", 'noðe', "sú", 'to commit a crime/unjust deed', None),
word("nodhelu", "nôðelu", "m", "crime",
     [etymology("word",  "#nodhe", "nôðe"),
      etymology("affix", "#lu", "lu")]),
word("noshxi", "nóš-[xi]", "NUM", "ten", None),
word("noshzosu", "nóšzo", "sú", "break into ten pieces",
     [etymology("word",  "#noshxi", "nóš[xi]"),
      etymology("affix", "#izosu", "izo")]),
word("nutesu", 'nute', "sú", 'to go (to)', None),
word("ny", 'ny', 'DEM', 'some', None)
]),
    ('O', [
word("obe", "ôbe", "k", "follower", None),
word("obesu", "ôbe", "sú", "to follow", None),
word("obesli", "ôbesli", "k", "stalker",
     [etymology("word", "#obe", "ôbe"),
      etymology("affix", "#sli", "sli")]),
word("ofra", "ôfra", "d", "hand", None),
word('ofrapash', "öfrapaš", "ADV/hy", "by hand",
     [etymology("word", '#ofra', "ôfra"),
      etymology("postposition", "#pash", "paš")]),
word("olea", "ôlea", "m", "rest, happiness", None),
word("oleazadisu", "ôleazadi", "sú", "to calm down (intrans.)",
     [etymology("word",  "#olea", "ôlea"),
      etymology("affix", "#izadisu", "izadi")]),
word("oleazosu", "ôleazo", "sú", "to calm down (trans.)",
     [etymology("word", "#olea", "ôlea"),
      etymology("affix", "#izosu", "izo")]),
word("omu", 'ômu', '*t', 'group', None),
word("omuli", "ômuli", "*t", "group, collection, set (~ mathematical)",
     [etymology("word", "#omu", "ômu"),
      etymology("affix", "#uli", "uli")]),
word("ono", 'ôno', "g", 'name', None),
word("onosu", 'ôno', "sú", 'to (give a) name', None),
word("onoge", "-önogé", "POST", "for (emph.), in the name of",
     [etymology("word", "#ono", "ôno"),
      etymology("postposition", "#ge", "gé")]),
word("onona", "ônona", "g", "old (former) name",
     [etymology("word", "#ono", "ôno"),
      etymology("affix", "#na", "na")]),
word("onovirma", "ônovirma", "m", "taxonomy",
     [etymology("word", "#ono", "ôno"),
      etymology("word", "#virma", "vírma")]),
word("ora", 'ôra', "m", 'day', None),
word("orna", "ôrna", "SUF", "desirous", None),
word("ornasu", "ôrna", "sú", "to desire", None),
word("hyornalu", "ôrnalu", "hy", "desired", None),
word("ornalu", "ôrnalu", "d", "desire", None),
word("ornapash", "örnapaš", "ADV", "willingly, voluntarily",
     [etymology("word", "#orna", "ôrna"),
      etymology("postposition", "#pash", "paš")]),
word("orpalo", "örpâlo", "g", "daylight",
     [etymology("word", "#ora", "ôra"),
      etymology("word", "#palo", "pâlo")]),
word("oska", "ôska", "k", "friendly foreigner", None),
word("ove", "ove[sa]", "j", "room", None),
]),
    ('P', [
word("palo", 'pâlo', "g", 'sun', None),
word("palol", "pâlol", "hy", "sunny",
     [etymology("word",  "#palo", "pâlo"),
      etymology("affix", "#il", "-il")]),
word("hypaplo", 'paplo', "hy", 'confused', None),
word("paplo", 'paplo', "m", 'confusion', None),
word("pare", 'páre[mo]', "m", "boat", None),
word("parsnau", "parsnaû", "k", "pirate",
     [etymology("word", "#pare", "päres"),
      etymology("word",  "#nauma", "naû(ma)")]),
word("penchu", "pénču", "g", "bus",
     [etymology("word", "#pendsteshu", "pëndstešu")]),
word("pendaine", "péndaîne", "k", "folk hero",
     [etymology("word", "#pendi", "péndi"),
      etymology("word", "#aine", "aîne")]),
word("pendgeno", "péndgêno", "g", "popular/national language",
     [etymology("word", "#pendi", "péndi"),
      etymology("word",  "#geno", "géno")]),
word("pendi", "péndi", "d", "the people", None),
word("hypendi", 'péndi', "hy", 'popular, national', None),
word("pendotesa", "péndotésa", "g", "Vox Populi",
     [etymology("word",  "#pendi", "péndi"),
      etymology("word",  "#tesa", "otêsa")]),
word("pendsteshu", "pëndstešu", "g", "bus",
     [etymology("word", "#pendi", "péndi"),
      etymology("word",  "#steshu", "stešu")]),
word("petuli", "pêtûli", "j", "mountain",
     [etymology("word", "#petu", "pêtu"),
      etymology("affix", "#uli", "uli")]),
word("petulira", "pëtûlira", "k", "mountaineer",
     [etymology("word", "#petuli", "pêtûli"),
      etymology("word", "#ra", "ra")]),
word("petuliravu", "pëtûlirävu", "ADV, hy", "like a mountaineer",
     [etymology("word", "#petulira", "pëtulira"),
      etymology("affix", "#evu", "evu")]),
word("pika", "pîka", "m", "story", None),
word("pikdem-wavra", "pïkdem wävra", "k", "bad musician (a musician without a song)",
     [etymology("word", "#pikdi", "pîkdi"),
      etymology("postposition", "#em", "em"),
      etymology("word", "#wavira", "wävra")]),
word("pikdi", "pîkdi", "m", "story song, ballad",
     [etymology("word", "#pika", "pîka"),
      etymology("word", "#dizhe", "di(ʒe)")]),
word("pikuli", "pîkuli", "m", "epic, saga",
     [etymology("word", "#pika", "pîka"),
      etymology("affix", "#uli", "uli")]),
word("pitare", "pitare", "d", "beginning", None),
word("plesu", "ple", "sú", "to love", None),
word("pleaku", "ple'âku", "k*, hy", "tree hugger",
     [etymology("affix", "#ple", "ple"),
      etymology("word", "#aku", "âku")]),
word("pledizhe", "plediʒe", "hy, k*", "music-lover",
     [etymology("affix", "#ple", "ple"),
      etymology("word",  "#dizhe", "diʒe")]),
word("pledzharhsi", "pledʒâŗsi", "hy, k*", "sweet-tooth",
     [etymology("affix", "#ple", "ple"),
      etymology("word", "#dzharhsi", "dʒâŗsi")]),
word("plehegi", "ple’egi", "hy", "loving the cold",
     [etymology("affix", "#ple", "ple"),
      etymology("word", "#egi", "égi")]),
word("plehevi", "ple’evi[zo]", "k*, hy", "pyromaniac",
     [etymology("affix", "#ple", "ple"),
      etymology("word", "#evi", "évi")]),
word("plefokla", "plefôkla", "hy", "loving the theatre",
     [etymology("affix", "#ple", "ple"),
      etymology("word",  "#fokla", "fôkla")]),
word("plegore", "plegore", "hy", "liking to run",
     [etymology("affix", "#ple", "ple"),
      etymology("word", "#gore", "gore")]),
word("plejavu", "plejávu", "hy", "traitorous (loving the enemy)",
     [etymology("affix", "#ple", "ple-"),
      etymology("word", "#javu", "javu")]),
word("plejedo", "plejedo", "hy", "loving wealth, greedy",
     [etymology("affix", "#ple", "ple"),
      etymology("word", "#jedo", "jédo")]),
word("plekashe", "plekaše", "k*, hy", "renaissance-man, one who likes many things",
     [etymology("affix", "#ple", "ple"),
      etymology("word",  "#kashe", "kaše")]),
word("plenasha", "plenaša", "hy", "peace-loving",
     [etymology("affix", "#ple", "ple"),
      etymology("word",  "#nasha", "náša")]),
word("pone", "pône", "ADV", "together", None),
word("ponezosu", "pônezo", "sú", "join, connect, put together, add, addition",
     [etymology("word", "#pone", "pône"),
      etymology("affix", "#izosu", "izo")]),
word("ponezolu", "pônezolu", "g", "sum",
     [etymology("word", "#ponezosu", "pônezo"),
      etymology("affix", "#lu", "lu")]),
word("popa", "pôpa", "k", "countryman", None),
word("prezdencurna", "prézdencúrna", "hy, *k", "wanting to be president",
     [etymology("word", "#prezdentasu", "prézdenta"),
      etymology("affix", "#orna", "ôrna")]),
word("prezdenta", "prézdenta", "*k", "president", None),
word("prezdentasu", "prézdenta", "sú", "to be president", None),
word("puri", "púri", "j", "street", None),
]),
    ('R', [
word("radnelu", "radnelu", "hy", "left",
     [etymology("word", "#radnesu", "radne"),
      etymology("affix", "#lu", "lu")]),
word("radnesu", "radne", "sú", "to leave", None),
word("radnesuha", "radne—há", "sú", "abandon",
     [etymology("word", "#radnesu", "radne"),
      etymology("affix", "#ha", "há")]),
word("ravi", "raví", "k", "saint",
     [etymology("word", "#ra", "ra"),
      etymology("word",  "#vihi", "ví(hi)")]),
word("reli", "réli", "m", "battle", None),
word("relklosa", "rëlklôsa", "m", "war-glory, renown won in battle",
     [etymology("word",  "#reli", "réli"),
      etymology("word",  "#klosa", "klôsa")]),
word("relorna", "rëlôrna", "hy", "desiring/ready for war",
     [etymology("word",  "#reli", "réli"),
      etymology("affix", "#orna", "ôrna")]),
word("relpitare", "rëlpitare", "m", "the beginning of a war",
     [etymology("word", "#reli", "réli"),
      etymology("word",  "#pitare", "pitare")]),
word("relrete", "rëlrete", "g", "excellence in war",
     [etymology("word", "#reli", "réli"),
      etymology("word",  "#rete", "rete")]),
word("relrodaga", "rëlrodâga","m", "ending of war, treaty",
     [etymology("word", "#reli", "réli"),
      etymology("word",  "#rodaga", "rodâga")]),
word("reluli", "réluli", "m", "large battle, war",
     [etymology("word",  "#reli", "réli",),
      etymology("affix", "#uli", "uli")]),
word("reliva", "réliva", "k", "soldier", None),
word("renzi", "rénzi", "g", "body", None),
word("rodaga", "rodâga", "m", "ending, conclusion", None),
word("roma-k", "róma", "k", "laborer", None),
word("roma-m", "rôma", "m", "labor, struggle", None),
word("romasu", "rôma", "sú", "to work, labor", None),
word("roma", "rôma–há", "sú", "to toil, struggle", None),
word("rora", "rôra", "m", "today",
     [etymology("affix", "#ry", "ry-"),
      etymology("word", "ora", "ôra")]),
word("roras", "röras", "ADV", "today",
     [etymology("word", "#rora", "rôra"),
      etymology("affix", "#es", "–es")]),
word("runo", "rúno", "hy", "hidden", None),
word("runotesa", "runôtesa", "g", "hidden-speech, jargon, slang",
     [etymology("word", "#runo", "runo"),
      etymology("word", "#tesa", "otesa")]),
word("runotesasu", "runôtesa", "sú", "to speak in slang/jargon",
     [etymology("word",  "#runo", "runo"),
      etymology("word",  "#tesa", "otesa")]),
word("runozadisu", "runozadi", "sú", "to hide (one's self)",
     [etymology("word",  "#runo", "runo"),
      etymology("affix", "#izadisu", "izadi")]),
word("runozosu", "runozo", "sú", "to hide (trans.)",
     [etymology("word", "#runo", "runo"),
      etymology("affix", "#izosu", "izo")])
]),
    ('Ŗ', [
word("rhemu", "ŗêmu", "k", "rower", None),
word("rhemu", "ŗêmu", "sú", "to row", None),
word("rhemulbu", "ŗêmulbu", "hy", "row-able",
     [etymology("word", "#rhemu", "ŗêmu"),
      etymology("affix", "#elbu", "elbu")]),
word("rhemupsi", "ŗêmupsi", "hy", "capable of rowing",
     [etymology("word", "#rhemu", "ŗêmu"),
      etymology("word",  "#epsi", "epsi")]),
word("Rhoma", "Ŗôma", "j", "Rome (Italy)", None),
word("rhy", "ŗy", "DEM", "this (distant)", None),
]),
    ("S", [
word("savosu", "sâvo", "sú", "to see", None),
word("savoha", "sâvo-há", "k", "observer",
     [etymology("word", "#savosu", "sâvo"),
      etymology("affix", "#ha", "há")]),
word("savosuha", "sâvo-há", "sú", "to observe",
     [etymology("word", "#savosu", "sâvo"),
      etymology("affix", "#ha", "há")]),
word("savolu", "sâvolu", "*", "sight",
     [etymology("word", "#savosu", "sâvo"),
      etymology("affix", "#lu", "lu")]),
word("savoluha", "sâvoluhá", "m", "observation",
     [etymology("word", "#savosu", "sâvo"),
      etymology("affix", "#lu", "lu"),
      etymology("affix", "#ha", "há")]),
word("sebi", "sébi", "m", "meeting", None),
word("sebisu", "sébi", "sú", "to meet", None),
word("sebisuha", "sébi–há", "sú", "to face",
     [etymology("word", "#sebisu", "sébi"),
      etymology("affix", "#ha", "há")]),
word("seborna", "sébôrna", "hy", "battle ready",
     [etymology("word", "#sebisu", "sébi"),
      etymology("affix", "#orna", "ôrna")]),
word("sencha", "senča", "j", "river bank", None),
word("sengu", "sengu", "d", "motto", None),
word("Skota", "Skôta", "hy, k*", "Scot, Scottish", None),
word("sozu", "sôzu", "g", "machine", None),
word("steshu", "stešu", "g", "wagon, car", None),
word("sumi", "súmi", "m", "distance", None),
word("sumorna", "sümôrna", "hy", "longing to be away",
     [etymology("word", "#sumi", "súmi"),
      etymology("affix", "#orna", "ôrna")]),
word("suntesa", "súntêsa", "g", "telephone",
     [etymology("word", "#sumi", "súmi"),
      etymology("word", "#tesa", "têsa")]),
word("suntesto", "súntêsto", "g", "cellphone",
     [etymology("word", "#suntesa", "súntêsa"),
      etymology("affix", "#eto", "eto")]),
word("sungy", "súñgy-", "DEM", "over there",
     [etymology("word", "#sumi", "súmi"),
      etymology("affix", "#gy", "gy-")]),
word("sy", "sy", "DEM", "what, which (interrogative)", None)
     ]),
    ("Š", [
word("shekema", "šekêma", "k", "hermit",
     [etymology("word", "#shexi", "še"),
      etymology("word", "#kema", "kêma")]),
word("shekemasu", "šekêma", "sú", "to live alone",
     [etymology("word", "#shexi", "še"),
      etymology("word", "#kemasu", "kêma")]),
word("shekemorna", "šekêmôrna", "hy", "wanting to live alone",
     [etymology("word", "#shexi", "še"),
      etymology("word", "#kemasu", "kêma"),
      etymology("affix", "#orna", "ôrna")]),
word("shegenocil",  "šegënocil[ra]", "k", "monolingual, monoglot",
     [etymology("word", "#shexi", "še"),
      etymology("word", "#geno", "geno[c]"),
      etymology("postposition", "#il", "il")]),
word("shezadisu", "šezadi", "sú", "to be unified",
     [etymology("word", "#shexi", "še"),
      etymology("affix", "izadisu", "izadi")]),
word("shezosu", "šezo", "sú", "to unify (trans.)",
     [etymology("word", "#shexi", "še"),
      etymology("affix", "izosu", "izo")]),
word("shexi", "še[xi]", "NUM", "one (1)", None),
word("shibaba", "šibâba", "j", "silo",
     [etymology("affix", "#shi", "ši"),
      etymology("word", "#baba", "bâba")]),
word("shibeka", "šibeka", "j", "horse stall",
     [etymology("affix", "#shi", "ši"),
      etymology("word", "#beka", "beka")]),
word("shibenu", "šibenu", "j", "graveyard",
     [etymology("affix", "#shi", "ši"),
      etymology("word", "#benu", "benu")]),
word("shibula", "šibúla", "j", "cow-pen",
     [etymology("affix", "#shi", "ši"),
      etymology("word", "#bula", "búla")]),
word("shibylembami", "šibylembá[mi]", "j", "homeless shelter",
     [etymology("affix", "#shi", "ši"),
      etymology("word", "#bylem", "bylem"),
      etymology("word", "#bami", "bámi")]),
word("shidesha", "šideša", "j", "bar",
     [etymology("affix", "#shi", "ši"),
      etymology("word", "deshasu", "deša")]),
word("shifokla", "šifokla", "j", "theater",
     [etymology("affix", "#shi", "ši"),
      etymology("word", "#fokla", "fôkla")]),
word("shifunau", "šifunaû", "j", "fishing grounds (~waters)",
     [etymology("affix", "#shi", "ši"),
      etymology("word", "#funau", "funaû")]),
word("shifunauto", "šifunaûto", "j", "fishing hole",
     [etymology("word", "#shifunau", "šifunaû"),
      etymology("affix", "#eto", "eto")]),
word("shigeshi", "šigêši", "j", "restaurant",
     [etymology("affix", "#shi", "ši"),
      etymology("word", "#geshi", "geši")]),
word("shijavu", "šijavu", "j", '"place of the enemy", enemy\'s camp"',
     [etymology("affix", "#shi", "ši"),
      etymology("word", "#javu", "javu")]),
word("shijedo", "šijédo", "j", "bank, treasury",
     [etymology("affix", "#shi", "ši"),
      etymology("word", "#jedo", "jédo")]),
word("shikago", "šikâgo", "j", "place that stinks/reeks",
     [etymology("affix", "#shi", "ši"),
      etymology("word", "#kago", "kâgo")]),
word("shikuge", "šikuge", "j", "armory",
     [etymology("affix", "#shi", "ši"),
      etymology("word", "#kuge", "kuge")]),
word("shikyga", "šikyga", "j", "doghouse",
     [etymology("affix", "#shi", "ši"),
      etymology("word", "#kyga", "kyga")]),
word("shilare", "šilare", "j", "school, place of learning/teaching",
     [etymology("affix", "#shi", "ši"),
      etymology("word", "#lare", "lare")]),
word("shilaruli", "šilaruli", "j", "university",
     [etymology("word", "#shilare", "šilare"),
      etymology("affix", "#uli", "-uli")]),
word("shilemi", "šilémi", "j", "dormitory, bedroom",
     [etymology("affix", "#shi", "ši"),
      etymology("word", "#lemi", "lémi")]),
word("shilugazo", "šilugazo", "j", "hospital",
     [etymology("affix", "#shi", "ši"),
      etymology("word", "#lugzao", "lûgazo")]),
word("shilushi", "šiluši", "j", "watering hole",
     [etymology("affix", "#shi", "ši"),
      etymology("word", "#lushi", "luši")]),
word("shimatelu", "šimatelu", "j", "place of knowledge, e.g. college, monastery, etc.",
     [etymology("affix", "#shi", "ši"),
      etymology("word", "#matelu", "matelu")]),
word("shimisha", "šimiša", "j", "church, temple, place of worship",
     [etymology("affix", "#shi", "ši"),
      etymology("word", "#misha", "miša")]),
word("shineki", "šinéki", "j", "place of victory",
     [etymology("affix", "#shi", "ši"),
      etymology("word", "#neki", "néki")]),
word("shinodhe", "šinoðe", "j", "crime scene",
     [etymology("affix", "#shi", "ši"),
      etymology("word", "#nodhe", "nôðe")]),
word("shinute", "šinute", "j", "destination",
     [etymology("affix", "#shi", "ši"),
      etymology("word", "nutesu", "nute")]),
word("shioleana", "Ši’ôleana", "j", "old place of rest (~ Eden)",
     [etymology("affix", "#shi", "ši"),
      etymology("word", "#olea", "ôlea"),
      etymology("affix", "#na", "na")]),
word("shiotesa", "ši'otesa", "j", "assembly hall",
     [etymology("affix", "#shi", "ši"),
      etymology("word", "#tesa", "otêsa")]),
word("shipare", "šipare", "j", "boathouse",
     [etymology("affix", "#shi", "ši"),
      etymology("word", "#pare", "páre")]),
word("shipendi", "šipéndi", "j", "national land/territory",
     [etymology("affix", "#shi", "ši"),
      etymology("word", "pendi", "péndi")]),
word("shipitare", "šipitare", "j", "starting line, square one",
     [etymology("affix", "#shi", "ši"),
      etymology("word", "#pitare", "pitare")]),
word("shipopa", "šipôpa", "j", "fatherland",
     [etymology("affix", "#shi", "ši"),
      etymology("word", "#popa", "pôpa")]),
word("shireliva", "širéliva", "j", "soldier camp",
     [etymology("affix", "#shi", "ši"),
      etymology("word", "#reliva", "réliva")]),
word("shiroma", "širóma", "j", "workplace",
     [etymology("affix", "#shi", "ši"),
      etymology("word", "#romasu", "rôma")]),
word("shirhdosha", "šiŗdóša", "j", "factory",
     [etymology("affix", "#shi", "ši"),
      etymology("word", "#erhdosha", "eŗdoša")]),
word("shisebi", "šisébi", "j", "meeting place",
     [etymology("affix", "#shi", "ši"),
      etymology("word", "#sebisu", "sébi")]),
word("shisumizo", "šisúmizo", "j", "concentration camp",
     [etymology("affix", "#shi", "ši"),
      etymology("word", "sumizosu", "súmizo")]),
word("shitenga", "šitenga", "j", "market, place of business",
     [etymology("affix", "#shi", "ši"),
      etymology("word", "#tenga", "tenga")]),
word("shivashuli", "šivâšuli", "j", "palace",
     [etymology("affix", "#shi", "ši"),
      etymology("word", "vashuli", "vašuli")]),
word("shiwate", "šiwáte", "j", "auditorium",
     [etymology("affix", "#shi", "ši"),
      etymology("word", "#watesu", "wáte")]),
word("shizuve", "šizuve", "j", "law court",
     [etymology("affix", "#shi", "ši"),
      etymology("word", "#zuve", "zuve")])]),
    ("T", [
word("takisuha", "tákihá", "sú", "to invade", None),
word("takiha", "tákihá", "k", "invader", None),
word("takiluha", 'tákiluhá', "j", "invaded territory",
     [etymology("word", "#takisuha", "táki-há"),
      etymology("affix", "#lu", "-lu")]),
word("tebami", 'tebámi', "l", "married woman",
     [etymology("affix", "#te", "te-"),
      etymology("word", "#bami", "bámi")]),
word("tebula", "tebúla", "k", "one who owns a cow/cattle",
     [etymology("affix", "#te", "te-"),
      etymology("word", "#bula", "búla")]),
word("tebyli", "tebyli", "k", "homeowner",
     [etymology("affix", "#te", "te-"),
      etymology("word", "#byli", "byli")]),
word("tedheba", "teðeba", "hy", "suffering",
     [etymology("affix", "#te", "te-"),
      etymology("word", "#dheba", "ðeba")]),
word("tekashe", "tekaše", "hy, k", "rich (person)",
     [etymology("affix", "#te", "te-"),
      etymology("word", "#kashe", "kaše")]),
word("telyzadisu", "telyzadi", "sú", "to gain",
     [etymology("affix", "#te", "te-"),
      etymology("affix", "#lyga", "ly(ga)"),
      etymology("affix", "#izadisu", "izadi")]),
word("telyzosu", "telyzo", "sú", "to give",
     [etymology("affix", "#te", "te-"),
      etymology("affix", "#lyga", "ly(ga)"),
      etymology("affix", "#izosu", "izo")]),
word("temupege", "temupé(ge)", "hy", "full of suffering",
     [etymology("affix", "#te", "te-"),
      etymology("word", "#mupege", "mupége")]),
word("tenasha", "tenaša", "hy", "peaceful",
     [etymology("affix", "#te", "te-"),
      etymology("word", "#nasha", "naša")]),
word("tenga", "tenga", "g", "business", None),
word("tengra", "tëngra", "k", "businessman",
     [etymology("word", "#tenga", "tenga"),
      etymology("word", "#ra", "ra")]),
word("tengsozu", "tëngsozu", "g", "cash register",
     [etymology("word", "#tenga", "tenga"),
      etymology("word", "#sozu", "sozu")]),
word("tepaplo", 'tepaplo', 'hy', "confused",
     [etymology("affix", "#te", "te-"),
      etymology("word", "#paplo", "paplo")]),
word("tesa", "(o)têsa", "g", "voice, tongue", None),
word("tesasu", "tesa", "sú", "to talk (about)", None),
word("tesavolu", "tesavolu", "g", "photo album, picture book",
     [etymology("affix", "#te", "te-"),
      etymology("word", "#savolu", "sâvolu")]),
word("tesklosa", "tësklôsa", "m", "speech-glory, renown given to one with aptitude for linguistic/ rhetorical skill",
     [etymology("word", "#tesa", "têsa"),
      etymology("word", "#klosa", "klôsa")]),
word("tesra", "tësra", "*k", "orator",
     [etymology("word", "#tesa", "têsa"),
      etymology("word", "#ra", "ra")]),
word("testeshu", "testešu", "*k", "car-owner",
     [etymology("affix", "#te", "te-"),
      etymology("word", "#steshu", "stešu")]),
word("tesu", "te", "sú", "to have",
     [etymology("affix", "#te", "te-")]),
word("teteva", "teteva", "k", "married man",
     [etymology("affix", "#te", "te-"),
      etymology("word", "#teva", "teva")]),
word("teva", "teva", "l", "girl", None),
word("tevato", "teväto", "l", "little girl",
     [etymology("word", "#teva", "teva"),
      etymology("affix", "#eto", "-eto")]),
word("tixu", "tixú", "*j", "southwest", None),
word("tixuka", "tixüka", "*k", "southwestern(er)",
     [etymology("word", "#tixu", "tixu"),
      etymology("postposition", "#ka", "-ka")]),
word("tovesa", "t'ôvesa", "j", "building",
     [etymology("affix", "#te", "te"),
      etymology("word", "#ove", "ove(sa)")]),
word("tugenocil", "túgënocil", "hy", "bilingual, biglot",
     [etymology("word", "#tuxi", "tú"),
      etymology("word", "#geno", "géno-c"),
      etymology("affix", "#il", "-il")]),
word("tugenocilra", "túgënocil(ra)", "k", "bilingual, biglot",
     [etymology("word", "#tugenocil", "túgënocil"),
      etymology("word", "#ra", "(ra)")]),
word("tuxi", "tú[xi]", "NUM", "two", None),
word("tuzadisu", "túzadi", "sú", "to split in two (trans.)",
     [etymology("word", "#tuxi", "tú"),
      etymology("word", "#izadisu", "izadi")]),
word("tuzosu", "túzo", "sú", "to (be) split in two (intrans.)",
     [etymology("word", "#tuxi", "tú"),
      etymology("word", "#izosu", "izo")]),
]),
    ("Þ", [
word("tha", "þá", "PART", "A particle marking the truth of the previous statement. Also a word for 'yes'.", None),
word("thasu", "þású", "q", "truth",
     [etymology("affix", "#tha", "þá"),
      etymology("affix", "#su", "sú")]),
]),
    ("U", [
word("ufe", "ufe", "g", "fish", None),
word("ufezi", "úfezi", "d", "fish meat",
     [etymology("word", "#ufe", "úfe"),
      etymology("affix", "#zilo", "zi(lo)")]),
word("umo", "umo", "k", "holder", None),
word("umosu", "umo", "sú", "to hold", None),
]),
    ("V", [
word("vabe", "vabe", "j", "river", None),
word("varemi", "varém(ul)i", "g", "epitaph", None),
word("vasto", "vasto", "hy", "angry", None),
word("vastozadisu", "vastozadi", "sú", "to get angry",
     [etymology("word", "#vasto", "vasto"),
      etymology("affix", "#izadisu", "-izadi")]),
word("vastozosu", "vastozo", "sú", "to anger",
     [etymology("word", "#vasto", "vasto"),
      etymology("affix", "#izosu", "-izo")]),
word("vastozosuga", "vastozo-gá", "sú", "to agitate",
     [etymology("word", "#vasto", "vasto"),
      etymology("affix", "#izosu", "-izo"),
      etymology("affix", "#ga", "-gá")]),
word("vashe", "vaše", "k", "leader", None),
word("vashuli", "vašuli", "k", "king",
     [etymology("word", "#vashe", "vaše"),
      etymology("affix", "#uli", "uli")]),
word("vegi", "végi", "k", "writer", None),
word("vegisu", "végi", "sú", "to write", None),
word("vegisuha", "végi-há", "sú", "to write (something)", None),
word("végilu", "végilu", "d, hy", "writing, written",
     [etymology("word", "#vegi", "végi"),
      etymology("affix", "#lu", "-lu")]),
word("vihi", "víhi, ví", "hy", "good", None),
word("virma", "vírma", "k", "giver", None),
word("virmasu", "vírma", "sú", "give", None),
word("volpy", "volpy", "m", "complication", None),
word("hyvolpy", "volpy", "hy", "complicated", None),
word("hyvolpyku", "volpykû", "hy", "overly complicated",
     [etymology("word", "#hyvolpy", "volpy"),
      etymology("affix", "#ku", "-kû")]),
word("volpyzosu", "volpyzo", "sú", "to complicate",
     [etymology("word", "#hyvolpy", "volpy"),
      etymology("affix", "#izosu", "izo")]),
]),
    ('W', [
word("waihi", "waîhi", "j", "sea", None),
word("waihuli", "waîhuli", "j", "ocean",
     [etymology("word", "#waihi", "waîhi"),
      etymology("affix", "#uli", "uli")]),
word("wanla", "wánla", "sú", "to draw", None),
word("wanlalu", "wánlalu", "d", "drawing",
     [etymology("word", "#wanla", "wánla"),
      etymology("affix", "#lu", "-lu")]),
word("watesu", "wáte", "sú", "to hear, listen", None),
word("watesuha", "wáte-há", "sú", "to listen (intently)",
     [etymology("word", "#watesu", "wáte"),
      etymology("affix", "#ha", "há")]),
word("watelu", "wâtelu", "g", "sound",
     [etymology("word", "#watesu", "wáte"),
      etymology("affix", "#lu", "-lu")]),
word("wavi", "wávi", "m", "music",
     [etymology("word", "#watelu", "wátelu"),
      etymology("word", "#vihi", "víhi")]),
word("wavisu", "wávi", "sú", "sing, perform music", None),
word("wavifokla", "wävifôkla", "m", "musical performance",
     [etymology("word", "#wavi", "wávi"),
      etymology("word", "#fokla", "fôkla")]),
word("wavilare", "wävilâre", "k", "music teacher",
     [etymology("word", "#wavi", "wávi"),
      etymology("word", "#laresu", "lâre")]),
word("wavira", "wävira", "k", "musician",
     [etymology("word", "#wavi", "wávi"),
      etymology("word", "#ra", "ra")]),
word("wavivegi", "wávivégi", "k", "composer",
     [etymology("word", "#wavi", "wávi"),
      etymology("word", "#vegi", "végi")]),
word("wimblo", "wîmblo", "d", "solution", None),
word("wimblosu", "wîmblo", "sú", "to solve", None),
]),
    ("X", [
word("xa", "xa", "PART", "~ the colloquial prefix a- (go a-walking)", None),
word("xi", "xî[si]", "d", "number", None),
word("ximate", "xîmate", "m", "mathematics (number-knowledge)",
     [etymology("word", "#xi", "xi[si]"),
      etymology("word", "#mate", "mate")]),
word("ximatera", "xîmatera", "k", "mathematician",
     [etymology("word", "#ximate", "ximate"),
      etymology("word", "#ra", "ra")])
]),
    ("Z", [
word("zagenocil-ra", "zágënocil[ra]", "k", "trilingual, triglot",
     [etymology("word", "#zaxi", "zá-[xi]"),
      etymology("word", "#geno", "geno-[c]"),
      etymology("word", "#il", "-il"),
      etymology("word", "#ra", "ra")]),
word("zagosu", "zâgo", "sú", "to want, wish", None),
word("zaxi", "zá-[xi]", "NUM", "3", None),
word("ze", '-ze', 'SUF, PART', 'if', None),
word("hyzilo", "zilo", "hy", "small", None),
word("zilo", "zilo", "*d", "a small part of something", None),
word("zilozadisu", "zilozadi", "sú", "to shrink, become small",
     [etymology("word", "#zilo", "zilo"),
      etymology("affix", "#izadisu", "-izadi")]),
word("zilozosu", "zilozo", "sú", "to belittle, shrink (trans.)",
     [etymology("word", "#zilo", "zilo"),
      etymology("affix", "#izosu", "-izo")]),
word("zuvesu", "zuve", "sú", "to judge", None),
word("zuve", "zuve", "k", 'judge', None),
word("zuvelu", "zuvelu", "m", "judgment", [etymology("word", "#zuvesu", "zuve"),
                                           etymology("affix", "#lu", "lu")]),
word("zyv", "zyv", "m", "flower", None),
]),
    ("Ʒ", [
word("zhana", "ʒána", "g", "tree", None),
word("zhebrha", "ʒébŗa", "d", "step", None),
word("zhebrhasu", "ʒébŗa", "sú", "to take a step", None),
word("zhebrhasuga", "ʒébŗa-gá", "sú", "walk",
     [etymology("word", "#zhebrhasu", "ʒébrasú"),
      etymology("affix", "#ga", "gá")]),
word("zhebrhasugaha", "ʒébŗa-gáhá", "sú", "march",
     [etymology("word", "#zhebrhasuga", "ʒébrasúgá"),
      etymology("affix", "#ha", "há")]),
word("zhegusu", "ʒêgu", "sú", "to shake, mix", None),
word("zhirso", "ʒîrso", "d", "tomato", None),
word("zhome", "ʒôme", "j", "woods", None),
word("zhomra", "ʒömra", "k", "woodsman",
     [etymology("word", "#zhome", "ʒôme"),
      etymology("word", "#ra", "ra")]),
word("zhongu",  "ʒôngu", "hy", "short, lacking detail, simple", None),
word("hy-zhonguku", "ʒônguku", "d", "too short, having too little detail, overly simple",
     [etymology("word", "#zhongu", "ʒôngu"),
      etymology("affix", "#ku","kû")]),
word("zhonguku", "ʒônguku", "d", "something which is too short or lacking detail",
     [etymology("word", "#zhongu", "ʒôngu"),
      etymology("affix", "#ku", "kû")]),
word("zhonguzosu", "ʒônguzo", "sú", "shorten, simplify",
     [etymology("word", "#zhongu", "ʒôngu"),
      etymology("affix", "#izosu", "izo")]),
word("zhonguzolu", "ʒônguzolu", "g", "abbreviation",
     [etymology("word", "#zhonguzosu", "ʒônguzo"),
      etymology("affix", "#lu", "lu")]),
word("zhy", "ʒy-", "DEM", "what, which, (rel.)", None)
 ]),
])


@singledispatch
def serialize(obj):
    return obj


@serialize.register(word)
def _(wd: word):
    fields = wd._asdict()
    if wd.etymology is not None:
        fields['etymology'] = map(serialize, fields['etymology'])
    return fields


@serialize.register(etymology)
def _(etym: etymology):
    return etym._asdict()


def to_json(dictionary=words):
    return json.dumps(valmap(serialize, dictionary))

